# -*- mode: ruby -*-
# vi: set ft=ruby :
#ENV['VAGRANT_EXPERIMENTAL'] = 'disks'
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel8"
  config.vm.box_version = "3.6.8"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/provisioning.yml"
  end

  (1..3).each do |i|
    config.vm.define "ranchermgr#{i}" do |node|
      node.vm.hostname = "ranchermgr#{i}"
      node.vm.network "public_network", ip: "192.168.123.20#{i}", bridge: "eno1"

      #node.vm.disk :disk, size: "20GB", primary: false, name: "data"

      node.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.gui = false
        vb.name = "ranchermgr#{i}"
        vb.check_guest_additions = false
        vb.memory = "4096"
        vb.cpus = "2"
        vb.customize ["modifyvm", :id, "--groups", "/rancher"]
        vb.customize ["modifyvm", :id, "--audio", "none" ]
      end
    end
  end

  (1..5).each do |i|
    config.vm.define "k8snode#{i}" do |node|
      node.vm.hostname = "k8snode#{i}"
      node.vm.network "public_network", ip: "192.168.123.21#{i}", bridge: "eno1"

      #node.vm.disk :disk, size: "20GB", primary: false, name: "data"

      node.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.gui = false
        vb.name = "k8snode#{i}"
        vb.check_guest_additions = false
        vb.memory = "4096"
        vb.cpus = "2"
        vb.customize ["modifyvm", :id, "--groups", "/rancher"]
        vb.customize ["modifyvm", :id, "--audio", "none" ]
      end
    end
  end

end
