---
- name: Deploy a swarm
  hosts: all
  vars:
    docker_swarm_interface: eth1
    docker_compose_version: 1.29.2
    containerd_service_override: |
      [Service]
      LimitMEMLOCK=infinity

  pre_tasks:
    - name: update all
      package:
        name: "*"
        state: latest
    - name: create group docker
      group:
        name: docker
        state: present
    - name: create user
      user:
        name: dockeradm
        groups: docker
        append: yes
        state: present
    - name: Set vm.max_map_count
      sysctl:
        name: vm.max_map_count
        value: "262144"
  roles:
    - atosatto.docker-swarm
---
- name: Create lvm volumes
  hosts: node2,node3
  tasks:
    - name: install LVM programs
      package:
        name: lvm2
        state: present
    - name: Create a partition
      parted:
        device: /dev/sdb
        label: gpt
        name: esdata
        number: 1
        align: optimal
        part_start: 0%
        part_end: 100%
        state: present
        flags: [lvm]
    - name: Create pv
      lvg:
        pvs: /dev/sdb1
        vg: esvg
    - name: Create lvol
      lvol:
        lv: esdata
        vg: esvg
        size: 20G 
        state: present
    - name: Format lvol
      filesystem:
        fstype: ext4
        dev: /dev/mapper/esvg-esdata
        opts: "-L ESDATA"
    - name: Mount volume
      mount:
        src: /dev/mapper/esvg-esdata
        path: /es-data
        state: mounted
        fstype: ext4
    - name: Create elasticsearch datadir
      file:
        path: /es-data/elasticsearch
        owner: "1000"
        group: "1000"
        state: directory
