---
- name: Deploy a swarm
  hosts: all
  tags: deploySwarm
  vars:
    docker_swarm_interface: eth1
    docker_compose_version: 1.29.2
    containerd_service_override: |
      [Service]
      LimitMEMLOCK=infinity
    skip_swarm: yes
  pre_tasks:
    - name: update all
      package:
        name: "*"
        state: latest
    - name: create group docker
      group:
        name: docker
        state: present
    - name: create user
      user:
        name: dockeradm
        groups: docker
        append: yes
        state: present
    - name: Set vm.max_map_count
      sysctl:
        name: vm.max_map_count
        value: "262144"
  roles:
    - atosatto.docker-swarm