---
- name: Vagrant provisioning
  hosts: all
  become: true
  become_method: sudo
  vars:
    default_gw: 192.168.123.1

  tasks:
    - name: add cotterpin user
      user:
        name: cotterpin
        comment: Automation user
        password: "{{ 'thisisnotsafe' |password_hash('sha512', 'salt') }}"

    - name: setup cotterpin ssh key
      authorized_key:
        user: cotterpin
        key: "{{ lookup('file', './keys/cotterpin-id_rsa.pub') }}"

    - name: setup juanjo ssh key for cotterpin
      authorized_key:
        user: cotterpin
        key: "{{ lookup('file', './keys/juanjo-id_rsa.pub') }}"

    - name: setup sudoers
      copy:
        dest: /etc/sudoers.d/cotterpin
        content: "cotterpin ALL=(ALL) NOPASSWD:ALL"

    - name: install anthrax ca CentOS/RedHat
      copy:
        src: tls/anthraxca.crt
        dest: /etc/pki/ca-trust/source/anchors/anthraxca.crt
      notify: update ca trust
      when: "ansible_distribution != 'Ubuntu'"

    - name: install anthax ca Ubuntu
      copy:
        src: tls/anthraxca.crt
        dest: /usr/local/share/ca-certificates/anthraxca.crt
      notify: update ca-certificates
      when: "ansible_distribution == 'Ubuntu'"

    - name: delete NAT default route
      command:
        cmd: "ip route del default via 10.0.2.2"
      register: route_del
      failed_when: route_del.rc == 1

    - name: add default route through bridged interface
      command:
        cmd: "ip route add default via {{ default_gw }}"
      register: route_add
      failed_when: route_add.rc == 1

    - block:
      - name: Remove default route assignment through vagrant NAT interface
        lineinfile:
          line: DEFROUTE=no
          regexp: "^DEFROUTE="
          state: present
          path: /etc/sysconfig/network-scripts/ifcfg-eth0

      - name: Enable default route assignment through bridged interface
        lineinfile:
          line: DEFROUTE=yes
          regexp: "^DEFROUTE="
          state: present
          path: /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Add default gateway on bridged interface
        lineinfile:
          line: GATEWAY={{ default_gw }}
          regexp: "^GATEWAY="
          state: present
          path: /etc/sysconfig/network-scripts/ifcfg-eth1
      when: "ansible_distribution != 'Ubuntu'"

  handlers:
    - name: update ca trust
      command:
        cmd: update-ca-trust
    - name: update ca-certificates
      command:
        cmd: update-ca-certificates
